/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MENU_CADASTRO;

import BANCO.conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20171inf0171
 */
public class PACIENTE extends javax.swing.JFrame {

    /**
     * Creates new form PACIENTE
     */
    public PACIENTE() {
        initComponents();
    }

    public void consultapaciente() {
        try {
            //CONSULTAR PACIENTES CADASTRADOS
            DefaultTableModel grid0 = (DefaultTableModel) tabelapaciente.getModel();
            grid0.setNumRows(0);
            Connection conn = null;
            conexao bd = new conexao();
            conn = bd.getConnection();
            Statement stmt = null;
            ResultSet rs = null;

            String sqlConsulta = "Select idclientes, nome, idade, cpf, plano_saude from clientes order by idclientes";
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sqlConsulta);
            while (rs.next()) {
                String recebe_cod = Integer.toString(rs.getInt("idclientes"));
                String recebe_nome = rs.getString("nome");
                String recebe_idade = Integer.toString(rs.getInt("idade"));
                String recebe_ps = rs.getString("plano_saude");
                String recebe_cpf = rs.getString("cpf");
                // int recebe_rg = rs.getInt("rg");
                // Mostra os valores na JTable
                DefaultTableModel grid = (DefaultTableModel) tabelapaciente.getModel();
                grid.addRow(new String[]{recebe_cod, recebe_nome, recebe_idade, recebe_cpf, recebe_ps});

            }
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(PACIENTE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pesquisar = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelapaciente = new javax.swing.JTable();
        cpf = new javax.swing.JFormattedTextField();
        rg = new javax.swing.JFormattedTextField();
        idade = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        planosaude = new javax.swing.JComboBox<>();
        novo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Idade");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/dropper (1).png"))); // NOI18N
        jLabel3.setText("Cadastro paciente");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("CPF");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Possui plano de saúde");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("RG");

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/plus.png"))); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/change.png"))); // NOI18N
        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/delete.png"))); // NOI18N
        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/search.png"))); // NOI18N
        jButton6.setText("Pesquisar");
        jButton6.setToolTipText("Pesquisar por nome");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tabelapaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Idade", "CPF", "Plano de Saúde"
            }
        ));
        tabelapaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelapacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelapaciente);
        if (tabelapaciente.getColumnModel().getColumnCount() > 0) {
            tabelapaciente.getColumnModel().getColumn(4).setResizable(false);
        }

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/document.png"))); // NOI18N
        jButton7.setText("Consultar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        planosaude.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        planosaude.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        planosaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planosaudeActionPerformed(evt);
            }
        });

        novo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/plus blue.png"))); // NOI18N
        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Pesquisar por nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(planosaude, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(idade, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(novo)
                                    .addComponent(jButton3)
                                    .addComponent(jButton5)
                                    .addComponent(jButton7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))
                        .addContainerGap(32, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(planosaude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(novo)
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)
                                .addGap(15, 15, 15)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //GRAVAR PACIENTE
        try {
            cadastro cad = new cadastro();
            String recebenome = nome.getText();
            String recebeidade = idade.getText();
            int idade1 = Integer.parseInt(recebeidade);
            String recebecpf = cpf.getText();
            String receberg = rg.getText();
            int rg1 = Integer.parseInt(receberg);
            String recebeps = (String) (planosaude.getSelectedItem());
            
            System.out.println(recebenome + idade1 + recebecpf + rg1 + recebeps);

            Connection conn = null;
            // obtem Banco com o banco
            
            conexao bd = new conexao();
            conn = bd.getConnection();
            
            cad.setnomepaciente(recebenome);
            cad.setidadepaciente(idade1);
            cad.setcpfpaciente(recebecpf);
            cad.setrgpaciente(rg1);
            cad.setpspaciente(recebeps);
           
            cad.incluirpaciente(conn);
            consultapaciente();

            nome.setText("");
            idade.setText("");
            cpf.setText("");
            rg.setText("");
            

        } catch (SQLException ex) {
            Logger.getLogger(PACIENTE.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       try {
            //CONSULTAR PACIENTES CADASTRADOS
            DefaultTableModel grid0 = (DefaultTableModel) tabelapaciente.getModel();
            grid0.setNumRows(0);
            Connection conn = null;
            conexao bd = new conexao();
            conn = bd.getConnection();
            Statement stmt = null;
            ResultSet rs = null;
            String sqlConsulta = "select * from clientes where nome like '%" + pesquisar.getText()+"%'" ;
            stmt = conn.createStatement();
            PreparedStatement stm = null;
            rs = stmt.executeQuery(sqlConsulta);
            while (rs.next()) {
                String recebe_cod = Integer.toString(rs.getInt("idclientes"));
                String recebe_nome = rs.getString("nome");
                String recebe_idade = Integer.toString(rs.getInt("idade"));
                String recebe_ps = rs.getString("plano_saude");
                String recebe_cpf = rs.getString("cpf");
                // int recebe_rg = rs.getInt("rg");
                // Mostra os valores na JTable
                DefaultTableModel grid = (DefaultTableModel) tabelapaciente.getModel();
                grid.addRow(new String[]{recebe_cod, recebe_nome, recebe_idade, recebe_cpf, recebe_ps});

            }
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(PACIENTE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        consultapaciente();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tabelapacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelapacienteMouseClicked
        String var_cod;
        int var_Lin = 0;
        var_Lin = tabelapaciente.getSelectedRow(); //retorna um inteiro
        var_cod = tabelapaciente.getValueAt(var_Lin, 0).toString(); // Valor Chave da Tabela
        int codid = Integer.parseInt(var_cod);

        String codigo_paciente = (tabelapaciente.getValueAt(var_Lin, 0).toString());
        nome.setText(tabelapaciente.getValueAt(var_Lin, 1).toString());
        idade.setText(tabelapaciente.getValueAt(var_Lin, 2).toString());
        cpf.setText(tabelapaciente.getValueAt(var_Lin, 3).toString());
       
         try{   Connection conn = null;
            conexao bd = new conexao();
            conn = bd.getConnection();
            Statement stmt = null;
            ResultSet rs = null;
            String sqlConsulta = "select rg from clientes where idclientes=" + var_cod;
            stmt = conn.createStatement();
            PreparedStatement stm = null;
            rs = stmt.executeQuery(sqlConsulta);
            while (rs.next()) {
                
            int recebe_rg = rs.getInt("rg");
            rg.setText(Integer.toString(recebe_rg));

            }
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(PACIENTE.class.getName()).log(Level.SEVERE, null, ex);
        }         


    }//GEN-LAST:event_tabelapacienteMouseClicked

    private void planosaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planosaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planosaudeActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        nome.setEnabled(true);
        nome.setText("");
        cpf.setEnabled(true);
        cpf.setText("");
        rg.setEnabled(true);
        rg.setText("");
        idade.setEnabled(true);
        idade.setText("");
        planosaude.setEnabled(true);


    }//GEN-LAST:event_novoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //ALTERAR
        Connection conn = null;
        try {
            cadastro cad = new cadastro();
            conexao bd = new conexao();
            conn = bd.getConnection();
  
            // Altera dados do Aluno
            String recebenome = nome.getText();
            String recebeidade = idade.getText();
            int idade1 = Integer.parseInt(recebeidade);
            String recebecpf = cpf.getText();
          
            String recebeps = (String) (planosaude.getSelectedItem());
            int var_Lin = tabelapaciente.getSelectedRow();
            String var_cod = tabelapaciente.getValueAt(var_Lin, 0).toString(); // Valor Chave da Tabela
            int codid = Integer.parseInt(var_cod);
            cad.setnomepaciente(recebenome);
            cad.setidadepaciente(idade1);
            cad.setcpfpaciente(recebecpf);
            cad.setpspaciente(recebeps);
            cad.alterarpaciente(conn, codid);

            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
       
        
       consultapaciente();
        }  catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Alteração não realizada!");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       //EXCLUIR
       try{
       Connection conn = null;
       
            cadastro cad = new cadastro();
            conexao bd = new conexao();
            conn = bd.getConnection();
            int var_Lin = tabelapaciente.getSelectedRow();
            String var_cod = tabelapaciente.getValueAt(var_Lin, 0).toString(); // Valor Chave da Tabela
            int codid = Integer.parseInt(var_cod);
            cad.excluirpaciente(conn, codid);

            JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!");
                consultapaciente();
       } catch(Exception e){
       JOptionPane.showMessageDialog(null, "Exclusão não realizada!");
       }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PACIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PACIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PACIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PACIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PACIENTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JTextField idade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JButton novo;
    private javax.swing.JTextField pesquisar;
    private javax.swing.JComboBox<String> planosaude;
    private javax.swing.JFormattedTextField rg;
    private javax.swing.JTable tabelapaciente;
    // End of variables declaration//GEN-END:variables
}
