/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FARMACIA;

import BANCO.conexao;
import FARMACIA.principal_farmacia;
import MENU_CADASTRO.ConverteData;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20171inf0228
 */
public class cadastro_medicamentos extends javax.swing.JFrame {

    /**
     * Creates new form cadastro_medicamentos
     */
    public cadastro_medicamentos() {
        initComponents();
    }
    public void preencherfornecedores() {
        try {
            //CONSULTAR PACIENTES CADASTRADOS
            Connection conn = null;
            conexao bd = new conexao();
            conn = bd.getConnection();
            Statement stmt = null;
            ResultSet rs = null;

            String sqlConsulta = "Select nome from fornecedores order by nome";
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sqlConsulta);
            fornecedores.removeAllItems();
            while (rs.next()) {
                fornecedores.addItem(rs.getString("nome"));

            }
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(cadastro_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void consulta() {
        while (tabela.getModel().getRowCount() > 0) {
            ((DefaultTableModel) tabela.getModel()).removeRow(0);
        }
        try {
            Connection conn = null;
            conexao bd = new conexao();
            conn = bd.getConnection();

            Statement stmt = null;
            ResultSet rs = null;
            String sqlConsulta = "Select * from medicamentos order by idmedicamentos";
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sqlConsulta);
            while (rs.next()) {
                String recebe_id = rs.getString("idmedicamentos");
                String recebe_nome = rs.getString("nome");
                String recebe_laboratorio = rs.getString("laboratorio");
                String recebe_quantidade = rs.getString("quantidade");
                String recebe_validade = rs.getString("validade");

                // Mostra os valores na JTable
                
                ConverteData conv = new ConverteData();
                String data_convertida = conv.DataMostra(recebe_validade);
                
                DefaultTableModel grid = (DefaultTableModel) tabela.getModel();
                grid.addRow(new String[]{recebe_id, recebe_nome, recebe_laboratorio, recebe_quantidade, data_convertida});

            }
        } catch (SQLException ex) {
            Logger.getLogger(cadastro_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quantidade = new javax.swing.JFormattedTextField();
        validade = new javax.swing.JFormattedTextField();
        consultar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        enviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        atualizar = new javax.swing.JButton();
        fornecedores = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Nome");

        jLabel6.setText("Fornecedor");

        jLabel4.setText("Quantidade");

        jLabel5.setText("Prazo de validade");

        try {
            validade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/document.png"))); // NOI18N
        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/change.png"))); // NOI18N
        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/delete.png"))); // NOI18N
        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/plus.png"))); // NOI18N
        enviar.setText("enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Fornecedor", "Quantidade", "Prazo val"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/medicine.png"))); // NOI18N
        jLabel2.setText("Cadastro de medicamentos");

        atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/delete.png"))); // NOI18N
        atualizar.setText("Excluir medicamentos vencidos");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(validade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(enviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(consultar)
                                .addGap(18, 18, 18)
                                .addComponent(alterar)
                                .addGap(18, 18, 18)
                                .addComponent(excluir)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enviar)
                            .addComponent(consultar)
                            .addComponent(alterar)
                            .addComponent(excluir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1104, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        String recebe_nome = nome.getText();
        String recebe_laboratorio =(String) (fornecedores.getSelectedItem());
        String recebe_quantidade = quantidade.getText();
        String recebe_validade = validade.getText();
       // System.err.println("passou 3");
        principal_farmacia cad = new principal_farmacia();
        
         ConverteData conv = new ConverteData();
        String data_convertida = conv.DataGrava(recebe_validade);
        
        cad.setnome(recebe_nome);
        cad.setlaboratorio(recebe_laboratorio);
        cad.setvalidade(data_convertida);
        cad.setquantidade(recebe_quantidade);
        Connection conn = null;
        // obtem conexao com o banco
        // try {
        conexao bd = new conexao();
        conn = bd.getConnection();
        //  conn.setAutoCommit(false);
        try {
            cad.incluir(conn);
            consulta();
        } catch (SQLException ex) {
            Logger.getLogger(cadastro_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        

        // TODO add your handling code here:
    }//GEN-LAST:event_enviarActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        consulta();
    }//GEN-LAST:event_consultarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        String var_cod;

        int var_Lin = 0;
        var_Lin = tabela.getSelectedRow(); //retorna um inteiro
        var_cod = tabela.getValueAt(var_Lin, 0).toString(); // Valor Chave da Tabela
        int codid = Integer.parseInt(var_cod);

        nome.setText(tabela.getValueAt(var_Lin, 1).toString());
        fornecedores.setSelectedItem(tabela.getValueAt(var_Lin, 2).toString());
        quantidade.setText(tabela.getValueAt(var_Lin, 3).toString());
        validade.setText(tabela.getValueAt(var_Lin, 4).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaMouseClicked

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        Connection conn = null;

        conexao bd = new conexao();
        conn = bd.getConnection(); // Altera dados do Aluno
        principal_farmacia cad = new principal_farmacia();
        try {
            String recebe_nome = nome.getText();
            String recebe_laboratorio = (String) fornecedores.getSelectedItem();
            String recebe_quantidade = quantidade.getText();
            String recebe_validade = validade.getText();
            ConverteData conv = new ConverteData();
             String data_convertida = conv.DataGrava(recebe_validade);
            cad.setnome(recebe_nome);
            cad.setlaboratorio(recebe_laboratorio);
            cad.setquantidade(recebe_quantidade);
            cad.setvalidade(data_convertida);

            String var_cod;
            int var_Lin = 0;
            var_Lin = tabela.getSelectedRow(); //retorna um inteiro
            var_cod = tabela.getValueAt(var_Lin, 0).toString(); // Valor Chave da Tabela
            int codid = Integer.parseInt(var_cod);

            cad.alterar(conn, codid);
            consulta();
        } catch (SQLException ex) {
            Logger.getLogger(cadastro_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
        }

        // efetiva Alteração
// conn.commit();
        JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");

        // TODO add your handling code here:
    }//GEN-LAST:event_alterarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        Connection conn = null;

        principal_farmacia cad = new principal_farmacia();
        conexao bd = new conexao();
        conn = bd.getConnection();
        int var_Lin = tabela.getSelectedRow();
        String var_cod = tabela.getValueAt(var_Lin, 0).toString(); // Valor Chave da Tabela
        int codid = Integer.parseInt(var_cod);

        try {
            cad.excluir(conn, codid);
            consulta();
        } catch (SQLException ex) {
            Logger.getLogger(cadastro_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!");
        //consultapaciente();

        // TODO add your handling code here:
    }//GEN-LAST:event_excluirActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        Connection conn = null;

        principal_farmacia cad = new principal_farmacia();
        conexao bd = new conexao();
        conn = bd.getConnection();
        //int var_Lin = tabela.getSelectedRow();
        //String var_cod = tabela.getValueAt(var_Lin, 0).toString(); // Valor Chave da Tabela
        //int codid = Integer.parseInt(var_cod);

        try {
            cad.atualizar(conn);
            consulta();
        } catch (SQLException ex) {
            Logger.getLogger(cadastro_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!");
        //consultapaciente();

        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       preencherfornecedores();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro_medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro_medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro_medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro_medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro_medicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton consultar;
    private javax.swing.JButton enviar;
    private javax.swing.JButton excluir;
    private javax.swing.JComboBox<String> fornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JFormattedTextField quantidade;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField validade;
    // End of variables declaration//GEN-END:variables
}
